name: Deploy Quarto Site to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render Quarto website
        working-directory: docs
        run: quarto render 

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # VÃ©rifier et committer uniquement s'il y a des modifications
          if [[ $(git status --porcelain) ]]; then
            git add docs/
            git commit -m "Update Quarto website"
          fi
      
          # Pull avec gestion de fusion automatique (fast-forward only)
          git pull --rebase=false --strategy-option=theirs origin main
      
          # Pousser les modifications
          git push
          
